[package]
name = "suhi-test"
version = "0.1.0"
edition = "2021"

[dependencies]
yew = { version = "0.21", features = ["csr"] }
serde = { version = "1.0", features = ["derive"] }
web-sys = { version = "0.3", features = ["HtmlInputElement", "Window", "Document", "Element", "Node"] }